import Link from "next/link";

export default function HomePage() {
  return <>
    <section className="hero"><div className="container hero-grid"><div><span className="eyebrow">Your campus, connected</span><h1>Lost something?<br /><span>Find it here.</span></h1><p className="hero-copy">CampusFind makes it easy to report missing belongings, return found items, and reconnect your campus community.</p><div className="hero-actions"><Link href="/browse" className="button">Browse items <span>→</span></Link><Link href="/register" className="button button-ghost">Create an account</Link></div><div className="hero-note"><span className="avatar-stack"><i>J</i><i>M</i><i>A</i></span><span>Helping students find what matters</span></div></div><div className="hero-art"><div className="art-card art-card-main"><div className="art-top"><span className="type-label found">Found</span><span className="art-check">✓</span></div><div className="art-object">🎒</div><h3>Canvas backpack</h3><p>Found near the Student Union</p><div className="art-line" /></div><div className="art-card art-card-small"><span className="type-label lost">Lost</span><strong>Student ID card</strong><small>Library · today</small></div><span className="art-dot dot-one" /><span className="art-dot dot-two" /></div></div></section>
    <section className="container feature-strip"><div><span className="feature-icon">◎</span><h3>Report in seconds</h3><p>Share what you lost or found with the people who can help.</p></div><div><span className="feature-icon">⌕</span><h3>Search your campus</h3><p>Filter reports by type, category, location, and date.</p></div><div><span className="feature-icon">✓</span><h3>Return with confidence</h3><p>Claims are reviewed by campus admins before handover.</p></div></section>
    <section className="home-callout"><div className="container callout-inner"><div><span className="eyebrow">Ready when you are</span><h2>Every item has a story.<br />Help finish it.</h2></div><Link href="/reports/new" className="button button-light">Report an item →</Link></div></section>
  </>;
}
